import test from 'node:test';import assert from 'node:assert/strict';import {testDatabase} from './helpers/d1.mjs';import {collectYouTube,refreshYouTube} from '../src/youtube-collection.mjs';
import {addYouTubeChannel} from '../src/youtube-sources.mjs';
const id='AbCdEf123_-';
const metadata={id,snippet:{title:'서연',channelTitle:'채널',channelId:'UC123',publishedAt:'2026-09-20T00:00:00Z'},contentDetails:{duration:'PT3M'},status:{privacyStatus:'public',uploadStatus:'processed'}};
test('collector saves page before advancing and never auto-publishes',async()=>{const {DB,sqlite}=testDatabase();try{
 const env={DB,YOUTUBE_ENABLED:'true',YOUTUBE_COLLECTION_ENABLED:'true',YOUTUBE_API_KEY:'test'};
 const fetcher=async url=>Response.json(new URL(url).pathname.endsWith('/search')?{items:[{id:{videoId:id}}],nextPageToken:'next'}:{items:[metadata]});
 assert.equal((await collectYouTube(env,{fetcher})).status,'partial');assert.equal(sqlite.prepare('SELECT decision FROM youtube_videos').get().decision,'pending');assert.equal(sqlite.prepare("SELECT count(*) n FROM youtube_sources WHERE page_token='next'").get().n,1);
 sqlite.exec("UPDATE youtube_sources SET enabled=CASE WHEN page_token='next' THEN 1 ELSE 0 END,next_due_at=0; CREATE TRIGGER fail_save BEFORE UPDATE ON youtube_videos BEGIN SELECT RAISE(ABORT,'fail'); END");
 assert.equal((await collectYouTube(env,{fetcher})).status,'failed');assert.equal(sqlite.prepare("SELECT page_token FROM youtube_sources WHERE enabled=1").get().page_token,'next');
 }finally{sqlite.close();}});
test('refresh expires cache even when feature is off and preserves human decisions',async()=>{const {DB,sqlite}=testDatabase();try{
 sqlite.prepare("INSERT INTO youtube_videos(video_id,metadata_json,metadata_fetched_at,decision,category,format) VALUES(?,'{}',0,'kept','fancam','regular')").run(id);
 await refreshYouTube({DB,YOUTUBE_ENABLED:'false'});const r=sqlite.prepare('SELECT * FROM youtube_videos').get();assert.equal(r.metadata_json,null);assert.equal(r.decision,'kept');assert.equal(r.availability,'expired');
 }finally{sqlite.close();}});
test('expired source lease cannot save metadata or advance a cursor',async()=>{const {DB,sqlite}=testDatabase();try{const env={DB,YOUTUBE_ENABLED:'true',YOUTUBE_COLLECTION_ENABLED:'true',YOUTUBE_API_KEY:'test'};await collectYouTube(env,{fetcher:async url=>{if(new URL(url).pathname.endsWith('/search'))return Response.json({items:[{id:{videoId:id}}],nextPageToken:'next'});sqlite.exec('UPDATE youtube_sources SET lease_until=0');return Response.json({items:[metadata]});}});assert.equal(sqlite.prepare('SELECT count(*) n FROM youtube_videos').get().n,0);assert.equal(sqlite.prepare('SELECT count(*) n FROM youtube_sources WHERE page_token IS NOT NULL').get().n,0);}finally{sqlite.close();}});
test('channel IDs are resolved officially and old upload pages do not backfill indefinitely',async()=>{const {DB,sqlite}=testDatabase();try{const env={DB,YOUTUBE_ENABLED:'true',YOUTUBE_COLLECTION_ENABLED:'true',YOUTUBE_API_KEY:'test'},channel='UC'+'a'.repeat(22),playlist='UU'+'a'.repeat(22);await addYouTubeChannel(env,{channel:'@music'},{fetcher:async()=>Response.json({items:[{id:channel,contentDetails:{relatedPlaylists:{uploads:playlist}}}]})});sqlite.exec("UPDATE youtube_sources SET enabled=0 WHERE kind='search'");const r=await collectYouTube(env,{fetcher:async()=>Response.json({items:[{contentDetails:{videoId:id,videoPublishedAt:'2020-01-01T00:00:00Z'}}],nextPageToken:'old'})});assert.equal(r.status,'ok');assert.equal(sqlite.prepare('SELECT count(*) n FROM youtube_videos').get().n,0);}finally{sqlite.close();}});
