import test from 'node:test';
import assert from 'node:assert/strict';
import {testDatabase} from './helpers/d1.mjs';
import {readOperationsState} from '../src/operations.mjs';
import {recordOperationsSnapshot,readOperationsHistory} from '../src/operations-history.mjs';
import {evaluateOperationsAlerts,readOperationsAlerts} from '../src/operations-alerts.mjs';
const setup=()=>{const d=testDatabase();return {...d,env:{DB:d.DB,YOUTUBE_ENABLED:'true',YOUTUBE_COLLECTION_ENABLED:'true',YOUTUBE_API_KEY:'not-exposed'}};};
test('operations includes YouTube counts in summaries and the alert evaluator input',async()=>{const {env,sqlite}=setup();try{sqlite.exec("INSERT INTO youtube_videos(video_id) VALUES('Pending1234'); INSERT INTO youtube_videos(video_id,decision,category,format) VALUES('Kept1234567','kept','fancam','regular'); UPDATE youtube_sources SET last_success_at=unixepoch()-30,next_due_at=unixepoch()+300");const full=await readOperationsState(env),small=await readOperationsState(env,{details:false});assert.equal(full.totals.youtube,2);assert.equal(full.youtube.status,'healthy');assert.equal(full.youtube.counts.pending,1);assert.equal(full.youtube.counts.kept,1);assert.equal(small.youtube.status,'healthy');assert.ok(!JSON.stringify(full).includes('not-exposed'));}finally{sqlite.close();}});
test('normal backfill cooldown and review backlog do not create delayed collection alerts',async()=>{const {env,sqlite}=setup();try{sqlite.exec("UPDATE youtube_sources SET last_success_at=unixepoch()-30,next_due_at=unixepoch()+300; INSERT INTO youtube_sources(source_key,kind,query,backfill_handle,window_start,window_end,backfill_until,last_success_at) VALUES('backfill:test','search','윤서연','@music','2022-01-01','2024-01-01','2026-08-22',unixepoch()-60)");let yt=(await readOperationsState(env)).youtube;assert.equal(yt.status,'healthy');assert.equal(yt.sources.find(s=>s.mode==='backfill').status,'scheduled');for(let i=0;i<20;i++)sqlite.prepare('INSERT INTO youtube_videos(video_id) VALUES(?)').run('Pending'+String(i).padStart(4,'0'));yt=(await readOperationsState(env)).youtube;assert.equal(yt.status,'healthy');assert.equal(yt.sources.find(s=>s.mode==='backfill').status,'review_wait');}finally{sqlite.close();}});
test('YouTube connection failure and overdue current sources are actionable while off is stopped',async()=>{const {env,sqlite}=setup();try{sqlite.exec("UPDATE youtube_sources SET last_success_at=unixepoch()-4000,next_due_at=unixepoch()-3000");assert.equal((await readOperationsState(env)).youtube.status,'delayed');sqlite.exec("UPDATE youtube_control SET last_error_code='provider_access',blocked_until=2147483647");assert.equal((await readOperationsState(env)).youtube.status,'attention');env.YOUTUBE_COLLECTION_ENABLED='false';assert.equal((await readOperationsState(env)).youtube.status,'disabled');}finally{sqlite.close();}});
test('YouTube history preserves unknown old totals and computes subsequent daily growth',async()=>{const {env,sqlite}=setup();try{sqlite.exec("INSERT INTO operations_history(day,captured_at,x_total,instagram_total,manual_total,query_version,query_status) VALUES('2026-09-19','2026-09-19T00:00:00Z',0,0,0,'x-review-v1','ok'); INSERT INTO youtube_videos(video_id) VALUES('OldCam12345')");await recordOperationsSnapshot(env,Date.parse('2026-09-20T00:00:00Z'));sqlite.exec("INSERT INTO youtube_videos(video_id) VALUES('NewCam12345')");await recordOperationsSnapshot(env,Date.parse('2026-09-21T00:00:00Z'));const {items}=await readOperationsHistory(env.DB,Date.parse('2026-09-21T00:00:00Z'));assert.equal(items[0].totals.youtube,2);assert.equal(items[0].delta.youtube,1);assert.equal(items[1].delta.youtube,null);assert.equal(items[2].totals.youtube,null);}finally{sqlite.close();}});
test('YouTube emits sustained problem and recovery events through the existing monitor',async()=>{const {env,sqlite}=setup();try{const start=Date.parse('2026-09-21T00:00:00Z');for(const [seconds,status] of [[0,'retry'],[300,'retry'],[600,'retry'],[900,'retry'],[1200,'healthy'],[1500,'healthy']])await evaluateOperationsAlerts(env,async()=>({youtube:{status}}),start+seconds*1000);const result=await readOperationsAlerts(env.DB,start+1500000);assert.deepEqual(result.events.filter(e=>e.key==='youtube').map(e=>e.type),['recovered','problem']);}finally{sqlite.close();}});

test('YouTube daily budget wait is not a failure and untrusted errors are sanitized',async()=>{const {env,sqlite}=setup();try{const day=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Los_Angeles',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());sqlite.prepare("INSERT INTO youtube_api_budget(day,bucket,calls) VALUES(?,'search',12)").run(day);sqlite.exec("UPDATE youtube_control SET last_error_code='quota_exceeded',blocked_until=unixepoch()+1000");assert.equal((await readOperationsState(env)).youtube.status,'quota_wait');sqlite.exec("UPDATE youtube_control SET last_error_code='private-token-in-error'");const data=await readOperationsState(env);assert.equal(data.youtube.error,'unknown_error');assert.ok(!JSON.stringify(data).includes('private-token'));}finally{sqlite.close();}});

test('search quota cannot hide overdue upload-channel collection',async()=>{const {env,sqlite}=setup();try{const day=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Los_Angeles',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());sqlite.prepare("INSERT INTO youtube_api_budget(day,bucket,calls) VALUES(?,'search',12)").run(day);sqlite.exec("INSERT INTO youtube_sources(source_key,kind,query,next_due_at,last_success_at) VALUES('channel:test','channel','UCtest',unixepoch()-4000,unixepoch()-5000)");const yt=(await readOperationsState(env)).youtube;assert.equal(yt.sources.find(s=>s.mode==='channel').status,'delayed');assert.equal(yt.status,'delayed');sqlite.exec("UPDATE youtube_sources SET last_error_code='quota_exceeded' WHERE kind='channel'");sqlite.exec("UPDATE youtube_control SET last_error_code='quota_exceeded',blocked_until=unixepoch()+86400");const failed=(await readOperationsState(env)).youtube;assert.equal(failed.sources.find(s=>s.mode==='channel').status,'retry');assert.equal(failed.status,'retry');}finally{sqlite.close();}});
