import {readFileSync} from 'node:fs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {testDatabase} from './helpers/d1.mjs';
import {collectYouTube} from '../src/youtube-collection.mjs';
const channel='UC'+'a'.repeat(22),id='OldCam12345';
function setup(){const db=testDatabase();db.sqlite.exec("UPDATE youtube_sources SET enabled=0; INSERT INTO youtube_sources(source_key,kind,query,backfill_handle,window_start,window_end,backfill_until) VALUES('backfill:m2','search','윤서연|SEOYEON','@MnetM2','2023-01-01T00:00:00.000Z','2024-01-01T00:00:00.000Z','2026-08-22T00:00:00.000Z')");return {...db,env:{DB:db.DB,YOUTUBE_ENABLED:'true',YOUTUBE_COLLECTION_ENABLED:'true',YOUTUBE_API_KEY:'fixture'}};}
function video(videoId=id,channelId=channel){return {id:videoId,snippet:{title:'윤서연 개인 직캠',channelId,channelTitle:'M2',publishedAt:'2023-02-16T00:00:00Z'},contentDetails:{duration:'PT3M'},status:{privacyStatus:'public',uploadStatus:'processed'}};}
function api({next,items=[video()],check=()=>{}}={}){return async input=>{const u=new URL(input);check(u);if(u.pathname.endsWith('/channels'))return Response.json({items:[{id:channel}]});if(u.pathname.endsWith('/search'))return Response.json({items:items.map(v=>({id:{videoId:v.id}})),...(next?{nextPageToken:next}:{})});return Response.json({items});};}
test('backfill searches the resolved official channel and advances annual windows after saving',async()=>{const {env,sqlite}=setup();try{const r=await collectYouTube(env,{fetcher:api({check:u=>{if(u.pathname.endsWith('/search')){assert.equal(u.searchParams.get('channelId'),channel);assert.equal(u.searchParams.get('maxResults'),'10');assert.equal(u.searchParams.get('publishedAfter'),'2023-01-01T00:00:00.000Z');}}})});assert.equal(r.status,'ok');assert.equal(sqlite.prepare('SELECT decision FROM youtube_videos').get().decision,'pending');const s=sqlite.prepare("SELECT * FROM youtube_sources WHERE source_key='backfill:m2'").get();assert.equal(s.window_start,'2024-01-01T00:00:00.000Z');assert.equal(s.window_end,'2025-01-01T00:00:00.000Z');assert.equal(s.backfill_channel_id,channel);}finally{sqlite.close();}});
test('backfill pauses on pending backlog without consuming requests or stopping latest collection',async()=>{const {env,sqlite}=setup();try{for(let i=0;i<20;i++)sqlite.prepare('INSERT INTO youtube_videos(video_id) VALUES(?)').run('Pending'+String(i).padStart(4,'0'));let calls=0;assert.equal((await collectYouTube(env,{fetcher:async()=>{calls++;return Response.json({items:[]});}})).status,'idle');assert.equal(calls,0);sqlite.exec("UPDATE youtube_sources SET enabled=1 WHERE source_key='search:ko-fancam'");assert.equal((await collectYouTube(env,{fetcher:api({items:[]})})).status,'ok');assert.equal(sqlite.prepare("SELECT window_start FROM youtube_sources WHERE source_key='backfill:m2'").get().window_start,'2023-01-01T00:00:00.000Z');}finally{sqlite.close();}});
test('backfill excludes wrong channels and preserves existing manual decisions',async()=>{const {env,sqlite}=setup();try{sqlite.prepare("INSERT INTO youtube_videos(video_id,decision,category,format,manual,revision) VALUES(?,'kept','fancam','regular',1,7)").run(id);const r=await collectYouTube(env,{fetcher:api({next:'page2',items:[video(),video('OtherCam123','UCwrong')]})});assert.equal(r.status,'partial');assert.equal(sqlite.prepare('SELECT count(*) n FROM youtube_videos').get().n,1);const v=sqlite.prepare('SELECT decision,manual,revision FROM youtube_videos').get();assert.deepEqual({...v},{decision:'kept',manual:1,revision:7});assert.equal(sqlite.prepare("SELECT page_token FROM youtube_sources WHERE source_key='backfill:m2'").get().page_token,'page2');}finally{sqlite.close();}});
test('backfill completes once and does not turn into a rolling recent search',async()=>{const {env,sqlite}=setup();try{sqlite.exec("UPDATE youtube_sources SET window_start='2026-01-01T00:00:00.000Z',window_end=backfill_until WHERE backfill_handle IS NOT NULL");await collectYouTube(env,{fetcher:api({items:[]})});assert.equal(sqlite.prepare("SELECT enabled FROM youtube_sources WHERE source_key='backfill:m2'").get().enabled,0);}finally{sqlite.close();}});
test('backfill save failure retains the period and cursor',async()=>{const {env,sqlite}=setup();try{sqlite.exec("CREATE TRIGGER fail_save BEFORE INSERT ON youtube_videos BEGIN SELECT RAISE(ABORT,'fail'); END");assert.equal((await collectYouTube(env,{fetcher:api({next:'page2'})})).status,'failed');const s=sqlite.prepare("SELECT * FROM youtube_sources WHERE source_key='backfill:m2'").get();assert.equal(s.page_token,null);assert.equal(s.window_start,'2023-01-01T00:00:00.000Z');assert.equal(sqlite.prepare('SELECT count(*) n FROM youtube_discoveries').get().n,0);}finally{sqlite.close();}});

test('backfill global cooldown preserves other channels and latest collection is preferred',async()=>{const {env,sqlite}=setup();try{sqlite.exec("INSERT INTO youtube_sources(source_key,kind,query,enabled,backfill_handle,last_success_at) VALUES('backfill:recent','search','윤서연',0,'@other',unixepoch())");let calls=0;assert.equal((await collectYouTube(env,{fetcher:async()=>{calls++;return Response.json({items:[]});}})).status,'idle');assert.equal(calls,0);sqlite.exec("UPDATE youtube_sources SET last_success_at=0; UPDATE youtube_sources SET enabled=1 WHERE source_key='search:ko-fancam'");await collectYouTube(env,{fetcher:api({items:[]})});assert.equal(sqlite.prepare("SELECT last_success_at FROM youtube_sources WHERE source_key='backfill:m2'").get().last_success_at,0);assert.ok(sqlite.prepare("SELECT last_success_at FROM youtube_sources WHERE source_key='search:ko-fancam'").get().last_success_at);}finally{sqlite.close();}});
test('backfill leaves the final four daily searches for latest discovery',async()=>{const {env,sqlite}=setup();try{const day=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Los_Angeles',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());sqlite.prepare("INSERT INTO youtube_api_budget(day,bucket,calls) VALUES(?,'search',8)").run(day);let calls=0;assert.equal((await collectYouTube(env,{fetcher:async()=>{calls++;return Response.json({items:[]});}})).status,'idle');assert.equal(calls,0);sqlite.exec("UPDATE youtube_sources SET enabled=1 WHERE source_key='search:ko-fancam'");assert.equal((await collectYouTube(env,{fetcher:api({items:[]})})).status,'ok');assert.equal(sqlite.prepare("SELECT calls FROM youtube_api_budget WHERE bucket='search'").get().calls,9);}finally{sqlite.close();}});
test('backfill pagination retains its period and next page stays channel scoped',async()=>{const {env,sqlite}=setup();try{await collectYouTube(env,{fetcher:api({next:'second',items:[]})});sqlite.exec("UPDATE youtube_sources SET last_success_at=0,next_due_at=0 WHERE backfill_handle IS NOT NULL");const r=await collectYouTube(env,{fetcher:api({items:[],check:u=>{if(u.pathname.endsWith('/search')){assert.equal(u.searchParams.get('pageToken'),'second');assert.equal(u.searchParams.get('channelId'),channel);assert.equal(u.searchParams.get('publishedAfter'),'2023-01-01T00:00:00.000Z');}}})});assert.equal(r.status,'ok');const s=sqlite.prepare("SELECT * FROM youtube_sources WHERE source_key='backfill:m2'").get();assert.equal(s.window_start,'2024-01-01T00:00:00.000Z');assert.equal(s.page_token,null);}finally{sqlite.close();}});

test('activation is idempotent and does not reset progress or latest sources',()=>{const {sqlite}=testDatabase();try{const previous=sqlite.prepare('SELECT * FROM youtube_sources ORDER BY source_key').all();const seed=readFileSync(new URL('../scripts/youtube-backfill.sql',import.meta.url),'utf8');sqlite.exec(seed);assert.equal(sqlite.prepare('SELECT count(*) n FROM youtube_sources WHERE backfill_handle IS NOT NULL').get().n,4);sqlite.exec("UPDATE youtube_sources SET page_token='saved-page',window_start='2024-01-01T00:00:00.000Z',enabled=0 WHERE backfill_handle IS NOT NULL");const saved=sqlite.prepare('SELECT * FROM youtube_sources ORDER BY source_key').all();sqlite.exec(seed);assert.deepEqual(sqlite.prepare('SELECT * FROM youtube_sources ORDER BY source_key').all(),saved);assert.deepEqual(sqlite.prepare('SELECT * FROM youtube_sources WHERE backfill_handle IS NULL ORDER BY source_key').all(),previous);}finally{sqlite.close();}});

test('backfill distinguishes Yoon Seoyeon from other groups with the same English name',async()=>{const {env,sqlite}=setup();try{const other=video('LeeSeoYeon1');other.snippet.title="[K-Fancam] 프로미스나인 이서연 직캠 (fromis_9 LEE SEO YEON Fancam)";const target=video();target.snippet.title="[MPD직캠] 트리플에스 서연 직캠 (tripleS SEOYEON FanCam)";await collectYouTube(env,{fetcher:api({items:[other,target]})});assert.deepEqual(sqlite.prepare('SELECT video_id FROM youtube_videos').all().map(r=>r.video_id),[id]);}finally{sqlite.close();}});
