import {createServer} from 'node:http';import {readFileSync,mkdirSync} from 'node:fs';import assert from 'node:assert/strict';import {chromium} from 'playwright';
import {testDatabase} from '../tests/helpers/d1.mjs';import {handleApi} from '../src/worker.mjs';
const {DB,sqlite}=testDatabase(),env={DB,YOUTUBE_ENABLED:'true',YOUTUBE_API_KEY:'fixture',MANUAL_MEDIA_ENABLED:'true'},actor={actor:{id:'owner@local.test'}},originalFetch=globalThis.fetch;
const id='AbCdEf123_-';globalThis.fetch=async(url,options)=>String(url).includes('/youtube/v3/channels')?Response.json({items:[{id:'UCabcdefghijklmnopqrstuv',snippet:{title:'검증 채널'},contentDetails:{relatedPlaylists:{uploads:'UUabcdefghijklmnopqrstuv'}}}]}):String(url).startsWith('https://www.googleapis.com/youtube/')?Response.json({items:[{id,snippet:{title:'서연 개인 직캠 · 테스트 영상',channelId:'UCfixture',channelTitle:'테스트 채널',publishedAt:'2026-09-20T00:00:00Z',thumbnails:{high:{url:`https://i.ytimg.com/vi/${id}/hqdefault.jpg`}}},contentDetails:{duration:'PT3M12S'},status:{privacyStatus:'public',uploadStatus:'processed'}}]}):originalFetch(url,options);
const server=createServer(async(req,res)=>{try{const url=new URL(req.url,'http://127.0.0.1:4198');if(req.headers.host!=='127.0.0.1:4198'){res.writeHead(403).end();return;}if(url.pathname==='/api/session'){res.setHeader('Content-Type','application/json');res.end('{"role":"owner"}');return;}if(url.pathname.startsWith('/api/')){const chunks=[];for await(const c of req)chunks.push(c);const response=await handleApi(new Request(url,{method:req.method,headers:req.headers,...(['POST','PATCH'].includes(req.method)?{body:Buffer.concat(chunks)}:{})}),env,actor);res.writeHead(response.status,Object.fromEntries(response.headers));res.end(await response.text());return;}
 const file=url.pathname==='/admin/x'?'x-review.html':url.pathname==='/admin/instagram'?'instagram.html':url.pathname==='/admin/youtube'?'youtube.html':url.pathname==='/admin/review-history'?'review-history.html':url.pathname.slice(1)||'feed.html';if(!/^[a-z-]+\.(html|js|css)$/.test(file)){res.writeHead(404).end();return;}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(readFileSync('validation/'+file));}catch(e){res.writeHead(500).end(e.message);}});
await new Promise(r=>server.listen(4198,'127.0.0.1',r));let browser;mkdirSync('.local',{recursive:true});
try{browser=await chromium.launch({headless:true,channel:'chrome'});const page=await browser.newPage({viewport:{width:360,height:800}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('https://i.ytimg.com/**',route=>route.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a2ioAAAAASUVORK5CYII=','base64')}));
 await page.goto('http://127.0.0.1:4198/?data=live&manage=tools');await page.locator('#manual-url').fill('https://youtube.com/shorts/'+id);await page.locator('#manual-submit').click();await page.getByText('게시물 URL과 확인 항목을 확인해 주세요. Shorts는 등록하지 않아요.',{exact:true}).waitFor();await page.locator('#manual-url').fill('https://youtu.be/'+id);await page.locator('#manual-submit').click();await page.locator('#youtube-confirm').waitFor();assert.deepEqual(await page.locator('#youtube-category option').allTextContents(),['개인 직캠','외부 출연','COSMO 라이브','공식 콘텐츠','기타']);await page.locator('#youtube-category').selectOption('cosmo_live');await page.locator('#youtube-confirm').check();await page.locator('#manual-submit').click();await page.getByText('유튜브에 등록했어요.',{exact:true}).waitFor();await page.locator('#close-status').click();await page.locator('[data-media=youtube]').click();await page.locator('.card').waitFor();assert.equal(await page.locator('.card').count(),1);assert.equal(await page.locator('#kind').isDisabled(),true);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'.local/youtube-feed-mobile.png'});
 await page.locator('[data-media=video]').click();await page.locator('#empty').waitFor({state:'visible'});await page.locator('[data-media=youtube]').click();await page.locator('.card').waitFor();await page.setViewportSize({width:768,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.locator('[data-media=youtube]').focus();await page.keyboard.press('Tab');assert.ok(await page.evaluate(()=>document.activeElement?.tagName!=='BODY'));await page.setViewportSize({width:1280,height:900});await page.screenshot({path:'.local/youtube-feed-desktop.png'});
 await page.goto('http://127.0.0.1:4198/admin/youtube');await page.locator('[data-status=kept]').click();await page.locator('.youtube-review').first().waitFor();assert.equal(await page.locator('.youtube-review select').first().inputValue(),'cosmo_live');await page.locator('.youtube-review select').first().selectOption('official');await page.getByRole('button',{name:'보류',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('.youtube-review'));await page.locator('[data-status=held]').click();await page.locator('.youtube-review').first().waitFor();assert.equal(await page.locator('.youtube-review select').first().inputValue(),'official');await page.locator('.youtube-review select').first().selectOption('other');await page.getByRole('button',{name:'제외',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('.youtube-review'));assert.equal(sqlite.prepare('SELECT decision FROM youtube_videos').get().decision,'excluded');await page.locator('[data-status=excluded]').click();await page.locator('.youtube-review').first().waitFor();await page.screenshot({path:'.local/youtube-review-desktop.png'});await page.setViewportSize({width:360,height:800});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'.local/youtube-review-mobile.png'});

 // Bulk moderation uses the existing revision-checked API and preserves per-video history.
 for(let i=0;i<3;i++)sqlite.prepare("INSERT INTO youtube_videos(video_id,metadata_json,metadata_fetched_at) VALUES(?,?,unixepoch())").run('Bulk000000'+i,JSON.stringify({title:'서연 직캠 '+i,durationSeconds:20,publishedAt:'2026-09-20T00:00:00Z',channelTitle:'검증 채널'}));
 await page.locator('[data-status=pending]').click();await page.locator('.youtube-select').first().waitFor();await page.locator('#youtube-select-all').check();assert.equal(await page.locator('.youtube-select:checked').count(),3);
 await page.locator('[data-status=kept]').click();await page.waitForFunction(()=>!document.querySelector('.youtube-review'));assert.equal(await page.locator('#youtube-bulk-apply').isDisabled(),true);
 await page.locator('[data-status=pending]').click();await page.locator('.youtube-select').first().waitFor();await page.locator('#youtube-select-all').check();
 sqlite.exec("UPDATE youtube_videos SET revision=revision+1,decision='held' WHERE video_id='Bulk0000001'");
 await page.locator('#youtube-bulk-action').selectOption('excluded');await page.locator('#youtube-bulk-reason').selectOption('COLLECTION_SCOPE');await page.locator('#youtube-bulk-apply').click();await page.getByText('2개 제외 · 1개 처리 실패. 목록을 새로고침해 확인해 주세요.',{exact:true}).waitFor();
 assert.equal(sqlite.prepare("SELECT decision FROM youtube_videos WHERE video_id='Bulk0000001'").get().decision,'held');assert.equal(sqlite.prepare("SELECT count(*) n FROM youtube_review_events WHERE reason_code='COLLECTION_SCOPE'").get().n,2);
 assert.equal(await page.locator('.youtube-select:checked').count(),0);await page.locator('#youtube-refresh').click();await page.waitForFunction(()=>!document.querySelector('.youtube-review'));

 // Excluded rows can be bulk restored; no publication without explicit classification and confirmation.
 await page.locator('[data-status=excluded]').click();await page.locator('.youtube-select').first().waitFor();await page.locator('#youtube-select-all').check();assert.equal(await page.locator('.youtube-select:checked').count(),3);
 await page.locator('#youtube-bulk-action').selectOption('kept');assert.equal(await page.locator('#youtube-bulk-reason').isVisible(),false);assert.equal(await page.locator('#youtube-bulk-apply').isDisabled(),true);
 await page.locator('#youtube-bulk-category').selectOption('fancam');assert.equal(await page.locator('#youtube-bulk-apply').isDisabled(),true);await page.locator('#youtube-bulk-confirm').check();
 await page.locator('#youtube-bulk-apply').click();await page.getByText('3개를 피드에 표시했어요.',{exact:true}).waitFor();assert.equal(sqlite.prepare("SELECT count(*) n FROM youtube_videos WHERE decision='kept' AND category='fancam' AND format='regular'").get().n,3);
 assert.equal(await page.locator('#youtube-bulk-controls').isVisible(),false);assert.equal(await page.locator('#youtube-bulk-confirm').isChecked(),false);
 await page.locator('[data-status=kept]').click();await page.locator('.youtube-review').first().waitFor();await page.locator('#youtube-select-all').check();await page.locator('#youtube-bulk-action').selectOption('excluded');await page.locator('#youtube-bulk-apply').click();await page.getByText('3개를 제외했어요. 제외 탭에서 다시 검토할 수 있어요.',{exact:true}).waitFor();

 // Unavailable video stays held and is reported as a failed publication.
 await page.locator('[data-status=held]').click();await page.locator('.youtube-select').first().waitFor();await page.locator('#youtube-select-all').check();await page.locator('#youtube-bulk-action').selectOption('kept');await page.locator('#youtube-bulk-category').selectOption('official');await page.locator('#youtube-bulk-confirm').check();
 sqlite.exec("UPDATE youtube_videos SET availability='unavailable',metadata_json=NULL WHERE video_id='Bulk0000001'");await page.locator('#youtube-bulk-apply').click();await page.getByText('0개 표시 · 1개 처리 실패. 목록을 새로고침해 확인해 주세요.',{exact:true}).waitFor();assert.equal(sqlite.prepare("SELECT decision FROM youtube_videos WHERE video_id='Bulk0000001'").get().decision,'held');
 await page.goto('http://127.0.0.1:4198/?data=live&manage=tools');await page.locator('#manual-url').fill('https://www.youtube.com/watch?v='+id);await page.locator('#manual-submit').click();await page.getByText('이미 저장된 영상이에요. 기존 검토 상태를 유지합니다.',{exact:true}).waitFor();assert.equal(sqlite.prepare('SELECT count(*) n FROM youtube_videos WHERE video_id=?').get(id).n,1);
 await page.goto('http://127.0.0.1:4198/admin/review-history');await page.locator('#history-platform').selectOption('YOUTUBE');await page.locator('.history-entry').first().waitFor();assert.ok(await page.locator('.history-entry').count()>=2);
 await page.goto('http://127.0.0.1:4198/?data=live&manage=collection');await page.locator('#youtube-collection').waitFor({state:'visible'});await page.locator('#youtube-collection summary').click();await page.locator('#youtube-channel').fill('@testchannel');await page.locator('#youtube-channel-form button').click();await page.getByText('검증 채널 채널을 추가했어요.',{exact:true}).waitFor();assert.equal(sqlite.prepare("SELECT count(*) n FROM youtube_sources WHERE kind='channel'").get().n,1);await page.locator('#youtube-retry').click();await page.getByText('다음 예약 실행에서 연결을 다시 확인해요.',{exact:true}).waitFor();assert.equal(await page.locator('#tools-panel a[href="/admin/youtube"]').count(),0);
 for(const width of [320,390,768,1280]){await page.setViewportSize({width,height:900});for(const route of ['x','instagram','youtube','review-history']){await page.goto('http://127.0.0.1:4198/admin/'+route);const links=page.locator('.review-nav a');assert.deepEqual(await links.evaluateAll(es=>es.map(e=>e.getAttribute('href'))),['/admin/x','/admin/instagram','/admin/youtube','/admin/review-history']);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,route+' overflow '+width);const sizes=await links.evaluateAll(es=>es.map(e=>({w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height,svg:e.querySelector('svg').getBoundingClientRect().width})));assert.ok(sizes.every(s=>s.w===44&&s.h===44&&s.svg===22),JSON.stringify({route,width,sizes}));if(route==='youtube'){await page.locator('[data-status=excluded]').click();await page.locator('.youtube-review').first().waitFor();await page.screenshot({path:'.local/youtube-aligned-'+width+'.png'});await page.locator('#youtube-select-all').check();await page.locator('#youtube-bulk-action').selectOption('kept');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'.local/youtube-bulk-selected-'+width+'.png'});assert.equal(await page.locator('#youtube-channel-form').count(),0);}}}
 assert.deepEqual(errors,[]);console.log('PASS: YouTube preview/register, tabs, review/exclude, duplicate protection, audit history and mobile/desktop layout');
}finally{await browser?.close();globalThis.fetch=originalFetch;await new Promise(r=>server.close(r));sqlite.close();}
