import {createServer} from 'node:http';import {readFileSync,mkdirSync} from 'node:fs';import assert from 'node:assert/strict';import {chromium} from 'playwright';
import {testDatabase} from '../tests/helpers/d1.mjs';import {handleApi} from '../src/worker.mjs';
const {DB,sqlite}=testDatabase(),env={DB,YOUTUBE_ENABLED:'true',YOUTUBE_API_KEY:'fixture',MANUAL_MEDIA_ENABLED:'true'},actor={actor:{id:'owner@local.test'}},originalFetch=globalThis.fetch;
const id='AbCdEf123_-';globalThis.fetch=async(url,options)=>String(url).startsWith('https://www.googleapis.com/youtube/')?Response.json({items:[{id,snippet:{title:'서연 개인 직캠 · 테스트 영상',channelId:'UCfixture',channelTitle:'테스트 채널',publishedAt:'2026-09-20T00:00:00Z',thumbnails:{high:{url:`https://i.ytimg.com/vi/${id}/hqdefault.jpg`}}},contentDetails:{duration:'PT3M12S'},status:{privacyStatus:'public',uploadStatus:'processed'}}]}):originalFetch(url,options);
const server=createServer(async(req,res)=>{try{const url=new URL(req.url,'http://127.0.0.1:4198');if(req.headers.host!=='127.0.0.1:4198'){res.writeHead(403).end();return;}if(url.pathname==='/api/session'){res.setHeader('Content-Type','application/json');res.end('{"role":"owner"}');return;}if(url.pathname.startsWith('/api/')){const chunks=[];for await(const c of req)chunks.push(c);const response=await handleApi(new Request(url,{method:req.method,headers:req.headers,...(['POST','PATCH'].includes(req.method)?{body:Buffer.concat(chunks)}:{})}),env,actor);res.writeHead(response.status,Object.fromEntries(response.headers));res.end(await response.text());return;}
 const file=url.pathname==='/admin/youtube'?'youtube.html':url.pathname==='/admin/review-history'?'review-history.html':url.pathname.slice(1)||'feed.html';if(!/^[a-z-]+\.(html|js|css)$/.test(file)){res.writeHead(404).end();return;}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(readFileSync('validation/'+file));}catch(e){res.writeHead(500).end(e.message);}});
await new Promise(r=>server.listen(4198,'127.0.0.1',r));let browser;mkdirSync('.local',{recursive:true});
try{browser=await chromium.launch({headless:true,channel:'chrome'});const page=await browser.newPage({viewport:{width:360,height:800}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('https://i.ytimg.com/**',route=>route.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a2ioAAAAASUVORK5CYII=','base64')}));
 await page.goto('http://127.0.0.1:4198/?data=live&manage=tools');await page.locator('#manual-url').fill('https://youtube.com/shorts/'+id);await page.locator('#manual-submit').click();await page.getByText('게시물 URL과 확인 항목을 확인해 주세요. Shorts는 등록하지 않아요.',{exact:true}).waitFor();await page.locator('#manual-url').fill('https://youtu.be/'+id);await page.locator('#manual-submit').click();await page.locator('#youtube-confirm').waitFor();await page.locator('#youtube-confirm').check();await page.locator('#manual-submit').click();await page.getByText('유튜브에 등록했어요.',{exact:true}).waitFor();await page.locator('#close-status').click();await page.locator('[data-media=youtube]').click();await page.locator('.card').waitFor();assert.equal(await page.locator('.card').count(),1);assert.equal(await page.locator('#kind').isDisabled(),true);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'.local/youtube-feed-mobile.png'});
 await page.locator('[data-media=video]').click();await page.locator('#empty').waitFor({state:'visible'});await page.locator('[data-media=youtube]').click();await page.locator('.card').waitFor();await page.setViewportSize({width:768,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.locator('[data-media=youtube]').focus();await page.keyboard.press('Tab');assert.ok(await page.evaluate(()=>document.activeElement?.tagName!=='BODY'));await page.setViewportSize({width:1280,height:900});await page.screenshot({path:'.local/youtube-feed-desktop.png'});
 await page.goto('http://127.0.0.1:4198/admin/youtube');await page.locator('#youtube-state').selectOption('kept');await page.locator('.youtube-review').waitFor();await page.getByRole('button',{name:'제외',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('.youtube-review'));assert.equal(sqlite.prepare('SELECT decision FROM youtube_videos').get().decision,'excluded');await page.locator('#youtube-state').selectOption('excluded');await page.locator('.youtube-review').waitFor();await page.screenshot({path:'.local/youtube-review-desktop.png'});await page.setViewportSize({width:360,height:800});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'.local/youtube-review-mobile.png'});
 await page.goto('http://127.0.0.1:4198/?data=live&manage=tools');await page.locator('#manual-url').fill('https://www.youtube.com/watch?v='+id);await page.locator('#manual-submit').click();await page.getByText('이미 저장된 영상이에요. 기존 검토 상태를 유지합니다.',{exact:true}).waitFor();assert.equal(sqlite.prepare('SELECT count(*) n FROM youtube_videos').get().n,1);
 await page.goto('http://127.0.0.1:4198/admin/review-history');await page.locator('#history-platform').selectOption('YOUTUBE');await page.locator('.history-entry').first().waitFor();assert.ok(await page.locator('.history-entry').count()>=2);assert.deepEqual(errors,[]);console.log('PASS: YouTube preview/register, tabs, review/exclude, duplicate protection, audit history and mobile/desktop layout');
}finally{await browser?.close();globalThis.fetch=originalFetch;await new Promise(r=>server.close(r));sqlite.close();}
