const $=s=>document.querySelector(s);let offset=0,loading=false,groupRevision=0,status='pending';
const node=(tag,text,cls)=>{const n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;return n;};
function link(url,text){const a=node('a',text,'review-link');a.href=url;a.target='_blank';a.rel='noopener noreferrer';return a;}
async function api(body){const r=await fetch('/api/admin/x?status='+status+'&offset='+offset,{...(body?{method:'POST',headers:{'Content-Type':'application/json','X-Review-Action':'review'},body:JSON.stringify(body)}:{})});if(!r.ok)throw Error(r.status===409?'다른 화면에서 변경됐어요. 새로고침해 주세요.':'불러오거나 저장하지 못했어요. 로그인 상태를 확인하고 다시 시도해 주세요.');return r.json();}
async function load(){if(loading)return;loading=true;try{let data=await api();if(offset>0&&offset>=data.total){offset=Math.max(0,Math.ceil(data.total/25)-1)*25;data=await api();}$('#empty').hidden=data.total!==0;$('#empty h2').textContent={pending:'지금 검토할 글이 없어요.',visible:'표시 중인 글이 없어요.',hidden:'숨긴 글이 없어요.',all:'아직 수집된 게시물이 없어요.'}[status];$('.pagination').hidden=data.total<=25;for(const b of document.querySelectorAll('#tabs button')){b.setAttribute('aria-pressed',String(b.dataset.status===status));b.querySelector('span').textContent=data.counts[b.dataset.status];}groupRevision=data.groupRevision;$('#items').replaceChildren(...data.items.map(card));$('#prev').disabled=offset===0;$('#next').disabled=offset+25>=data.total;$('#page').textContent=`${offset/25+1}페이지 · 전체 ${data.total}개`;}catch(e){$('#message').textContent=e.message;}finally{loading=false;}}
function card(p){const a=node('article',null,'review-card'),pictures=node('div'),body=node('div',null,'review-body');
 const media=p.media.filter(m=>m.previewUrl),gallery=window.reviewGallery(media.map((m,i)=>({src:m.previewUrl,url:p.canonicalUrl,alt:p.authorHandle+' 사진 '+(i+1)})),{label:'현재 사진',onChange:()=>renderComparison()});
 pictures.className='review-pictures';pictures.append(gallery.element);
 const comparison=node('section',null,'photo-comparison');comparison.setAttribute('aria-label','유사 게시물 비교');pictures.append(comparison);
 function renderComparison(){comparison.replaceChildren();const current=media[gallery.index];const candidates=p.comparisons.filter(c=>c.ownImage===current?.previewUrl);pictures.classList.toggle('has-comparison',candidates.length>0);comparison.hidden=!candidates.length;if(!candidates.length)return;
  const heading=node('p','유사 게시물','comparison-heading'),info=node('div',null,'comparison-info'),actions=node('div',null,'review-buttons');
  const other=window.reviewGallery(candidates.map(c=>({src:c.image,url:c.url,alt:'@'+c.author+' 비교 사진'})),{label:'후보',onChange:renderCandidate});
  comparison.append(heading,other.element,info,actions);renderCandidate(0);
  function renderCandidate(i){const c=candidates[i];info.replaceChildren(node('strong','@'+(c.author||'작성자 미상')),node('span',new Date(c.publishedAt).toLocaleDateString('ko-KR')),node('span',c.visible?'피드에 표시 중':'피드에서 숨김'),link(c.url,'원문 보기 ↗'));actions.replaceChildren();
   for(const [action,label] of (c.exact?[['unmerge','묶음 해제']]:[['merge','같은 사진으로 묶기'],['different','다른 사진']])){const b=node('button',label);b.onclick=async()=>{if(loading)return;actions.querySelectorAll('button').forEach(x=>x.disabled=true);try{await api(action==='unmerge'?{action,groupRevision,image:c.ownImage}:{action,groupRevision,left:c.ownImage,right:c.image});await load();}catch(e){$('#message').textContent=e.message;actions.querySelectorAll('button').forEach(x=>x.disabled=false);}};actions.append(b);}
   const hide=node('button','검토 중인 글 숨기기');hide.disabled=p.decision==='hidden';hide.onclick=async()=>{if(loading)return;hide.disabled=true;try{await api({id:p.id,revision:p.revision,decision:'hidden'});await load();}catch(e){$('#message').textContent=e.message;hide.disabled=false;}};actions.append(hide);
  }
 }
 const firstMatch=media.findIndex(m=>p.comparisons.some(c=>c.ownImage===m.previewUrl));if(firstMatch>=0)gallery.select(firstMatch,false);
 renderComparison();
 body.append(node('h2','@'+p.authorHandle),node('p',new Date(p.publishedAt).toLocaleDateString('ko-KR'),'muted'),node('p',p.visible?'피드에 표시 중':'피드에서 숨김','review-tags'));
 const reasons=[p.moderationReason,p.availability==='missing'?`원문 확인 불가 · ${p.missingCount}회 확인`:null,p.decision==='hidden'?'직접 숨긴 글':null,p.comparisons.some(c=>c.exact)?'동일 사진은 대표 글에서 한 번만 표시':null,p.comparisons.some(c=>!c.exact)?'비슷한 사진 후보 · 직접 비교 필요':null].filter(Boolean);
 reasons.forEach(r=>body.append(node('p',r,'review-reasons')));body.append(node('p',p.caption,'review-caption'),link(p.canonicalUrl,'원문 보기 ↗'));
 const actions=node('div',null,'review-buttons');for(const [decision,label] of [['hidden','숨기기'],['visible','피드 표시 허용'],['auto','자동 기준으로']]){const b=node('button',label);b.disabled=decision===p.decision;b.onclick=async()=>{actions.querySelectorAll('button').forEach(b=>b.disabled=true);try{await api({id:p.id,revision:p.revision,decision});await load();$('#message').textContent='판단을 저장했어요. 원문 확인 불가·동일 사진 처리는 별도로 유지돼요.';}catch(e){$('#message').textContent=e.message;actions.querySelectorAll('button').forEach(b=>b.disabled=false);}};actions.append(b);}body.append(actions);a.append(pictures,body);return a;}
for(const b of document.querySelectorAll('#tabs button'))b.onclick=()=>{if(loading)return;status=b.dataset.status;offset=0;load();};
$('#refresh').onclick=load;$('#prev').onclick=()=>{if(loading)return;offset=Math.max(0,offset-25);load();};$('#next').onclick=()=>{if(loading)return;offset+=25;load();};load();
