const $=s=>document.querySelector(s);let offset=0,loading=false,groupRevision=0,status='pending';
const node=(tag,text,cls)=>{const n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;return n;};
function link(url,text){const a=node('a',text,'review-link');a.href=url;a.target='_blank';a.rel='noopener noreferrer';return a;}
async function api(body){const r=await fetch('/api/admin/x?status='+status+'&offset='+offset,{...(body?{method:'POST',headers:{'Content-Type':'application/json','X-Review-Action':'review'},body:JSON.stringify(body)}:{})});if(!r.ok)throw Error(r.status===409?'다른 화면에서 변경됐어요. 새로고침해 주세요.':'불러오거나 저장하지 못했어요. 로그인 상태를 확인하고 다시 시도해 주세요.');return r.json();}
async function load(){if(loading)return;loading=true;try{let data=await api();if(offset>0&&offset>=data.total){offset=Math.max(0,Math.ceil(data.total/25)-1)*25;data=await api();}$('#empty').hidden=data.total!==0;for(const b of document.querySelectorAll('#tabs button')){b.setAttribute('aria-pressed',String(b.dataset.status===status));b.querySelector('span').textContent=data.counts[b.dataset.status];}groupRevision=data.groupRevision;$('#items').replaceChildren(...data.items.map(card));$('#prev').disabled=offset===0;$('#next').disabled=offset+25>=data.total;$('#page').textContent=`${offset/25+1}페이지 · 전체 ${data.total}개`;}catch(e){$('#message').textContent=e.message;}finally{loading=false;}}
function card(p){const a=node('article',null,'review-card'),pictures=node('div'),body=node('div',null,'review-body');
 for(const [i,m] of p.media.entries()){if(!m.previewUrl)continue;const anchor=link(p.canonicalUrl,'');const img=node('img');img.src=m.previewUrl;img.alt=`${p.authorHandle} 미디어 ${i+1}`;img.loading='lazy';img.style.width='100%';anchor.append(img);pictures.append(anchor);}
 body.append(node('h2','@'+p.authorHandle),node('p',new Date(p.publishedAt).toLocaleDateString('ko-KR'),'muted'),node('p',p.visible?'피드에 표시 중':'피드에서 숨김','review-tags'));
 const reasons=[p.moderationReason,p.availability==='missing'?`원문 확인 불가 · ${p.missingCount}회 확인`:null,p.decision==='hidden'?'직접 숨긴 글':null,p.comparisons.some(c=>c.exact)?'동일 사진은 대표 글에서 한 번만 표시':null,p.comparisons.some(c=>!c.exact)?'비슷한 사진 후보 · 직접 비교 필요':null].filter(Boolean);
 reasons.forEach(r=>body.append(node('p',r,'review-reasons')));body.append(node('p',p.caption,'review-caption'),link(p.canonicalUrl,'원문 보기 ↗'));
 if(p.comparisons.length){const details=node('details');details.append(node('summary','중복·유사 사진 비교'));for(const c of p.comparisons){const a=link(c.url,c.exact?'동일 사진 출처 ↗':'유사 사진 출처 ↗');const img=node('img');img.src=c.image;img.alt='비교할 사진';img.loading='lazy';img.style.width='120px';a.prepend(img);details.append(a);const b=node('button',c.exact?'이 사진 묶음 해제':'같은 사진으로 묶기');b.onclick=async()=>{b.disabled=true;try{await api(c.exact?{action:'unmerge',groupRevision,image:c.ownImage}:{action:'merge',groupRevision,left:c.ownImage,right:c.image});await load();}catch(e){$('#message').textContent=e.message;b.disabled=false;}};details.append(b);}body.append(details);}
 const actions=node('div',null,'review-buttons');for(const [decision,label] of [['hidden','숨기기'],['visible','피드 표시 허용'],['auto','자동 기준으로']]){const b=node('button',label);b.disabled=decision===p.decision;b.onclick=async()=>{actions.querySelectorAll('button').forEach(b=>b.disabled=true);try{await api({id:p.id,revision:p.revision,decision});await load();$('#message').textContent='판단을 저장했어요. 원문 확인 불가·동일 사진 처리는 별도로 유지돼요.';}catch(e){$('#message').textContent=e.message;actions.querySelectorAll('button').forEach(b=>b.disabled=false);}};actions.append(b);}body.append(actions);a.append(pictures,body);return a;}
for(const b of document.querySelectorAll('#tabs button'))b.onclick=()=>{if(loading)return;status=b.dataset.status;offset=0;load();};
$('#refresh').onclick=load;$('#prev').onclick=()=>{if(loading)return;offset=Math.max(0,offset-25);load();};$('#next').onclick=()=>{if(loading)return;offset+=25;load();};load();
