(()=>{
 const $=s=>document.querySelector(s),node=(tag,text)=>{const n=document.createElement(tag);if(text)n.textContent=text;return n;};
 const errors={youtube_disabled:'유튜브 기능이 중지돼 있어요.',not_configured:'YouTube API 키 설정을 확인해 주세요.',provider_access:'YouTube API 사용 설정과 키 권한을 확인해 주세요.',quota_exceeded:'오늘의 조회 한도에 도달했어요.',unavailable:'공개된 영상 정보를 확인할 수 없어요.',review_conflict:'다른 작업에서 상태가 바뀌었어요. 새로고침 후 다시 확인해 주세요.',invalid_input:'영상 종류와 일반 영상 확인 항목을 확인해 주세요.'};
 const labels={pending:'검토 대기',kept:'표시 중',held:'보류',excluded:'제외'};let cursor=null,generation=0;
 async function api(path,body,method='POST'){const r=await fetch(path,body?{method,headers:{'Content-Type':'application/json','X-Management-Action':'manage'},body:JSON.stringify(body)}:{});const d=await r.json();if(!r.ok)throw Error(r.status===401||r.status===403?'관리자 로그인 후 다시 열어 주세요.':errors[d.error]||'처리하지 못했어요. 새로고침 후 다시 시도해 주세요.');return d;}
 function option(label,values,value){const l=node('label',label),s=node('select');for(const [v,t]of values)s.add(new Option(t,v));s.value=value||'';l.append(s);return {label:l,select:s};}
 function card(p){const a=node('article');a.className='youtube-review';const preview=node('div'),body=node('div');if(p.metadata?.thumbnailUrl){const img=node('img');img.src=p.metadata.thumbnailUrl;img.alt=p.metadata.title;img.loading='lazy';img.referrerPolicy='no-referrer';img.onerror=()=>img.remove();preview.append(img);}const link=node('a','YouTube에서 보기');link.href=p.url;link.target='_blank';link.rel='noopener noreferrer';preview.append(link);if(p.discoveries?.length)body.append(node('p','발견 경로: '+p.discoveries.join(', ')));body.append(node('h2',p.metadata?.title||'영상 정보 확인 불가'),node('p',(p.metadata?.channelTitle||'채널 미확인')+' · '+labels[p.decision]),node('p',p.metadata?new Date(p.metadata.publishedAt).toLocaleDateString('ko-KR')+' · '+Math.floor(p.metadata.durationSeconds/60)+':'+String(Math.floor(p.metadata.durationSeconds%60)).padStart(2,'0'):'정보 갱신이 필요해요.'));
 const form=node('form'),category=option('관리자 분류',[['','종류 선택'],['fancam','개인 직캠'],['appearance','외부 출연']],p.category),reason=option('제외 사유',[['SHORTS','Shorts'],['GROUP_STAGE','단체 무대'],['NOT_SEOYEON','서연 출연 아님'],['REUPLOAD','재업로드'],['FAN_EDIT','팬 편집본'],['OTHER','기타']],'SHORTS');
 const confirm=node('label','서연이 출연한 일반 영상임을 확인했습니다.'),check=node('input');confirm.className='youtube-confirm';check.type='checkbox';check.checked=p.format==='regular';confirm.prepend(check);form.append(category.label,reason.label,confirm);
 const message=node('p');message.setAttribute('role','status');let requestId=crypto.randomUUID(),lastPayload=null;
 for(const [decision,label]of [['kept','피드에 표시'],['excluded','제외'],['held','보류'],['pending','검토 대기로']]){const b=node('button',label);b.type='button';b.disabled=decision==='kept'&&(p.availability!=='available'||!p.metadata);b.onclick=async()=>{const payload={revision:p.revision,decision,category:category.select.value||null,format:decision==='excluded'&&reason.select.value==='SHORTS'?'shorts':check.checked?'regular':'unknown',reasonCode:decision==='kept'?'SEOYEON_CONFIRMED':decision==='excluded'?reason.select.value:'NEEDS_REVIEW'};const fingerprint=JSON.stringify(payload);if(lastPayload!==fingerprint){requestId=crypto.randomUUID();lastPayload=fingerprint;}form.querySelectorAll('button').forEach(el=>el.disabled=true);try{await api('/api/youtube/review/'+p.videoId,{...payload,requestId},'PATCH');await load();}catch(e){message.textContent=e.message;form.querySelectorAll('button').forEach(el=>el.disabled=false);}};form.append(b);}
 body.append(form,message);a.append(preview,body);return a;}
 async function load(more=false){const version=++generation;$('#youtube-notice').textContent='불러오는 중…';$('#youtube-more').disabled=true;try{const q=new URLSearchParams({state:$('#youtube-state').value});if(more&&cursor)q.set('cursor',cursor);const data=await api('/api/youtube/review?'+q);if(version!==generation)return;if(!more)$('#youtube-list').replaceChildren();$('#youtube-list').append(...data.posts.map(card));cursor=data.nextCursor;$('#youtube-more').hidden=!cursor;$('#youtube-notice').textContent=data.enabled?data.counts.map(r=>labels[r.decision]+' '+r.count).join(' · '):'유튜브 기능이 중지되어 있어요.';}catch(e){if(version===generation)$('#youtube-notice').textContent=e.message;}finally{if(version===generation)$('#youtube-more').disabled=false;}}
 async function status(){try{const s=await api('/api/youtube/status');$('#youtube-status').textContent=(s.collectionEnabled?'자동 수집 사용':'자동 수집 중지')+' · '+(s.configured?'API 키 등록됨':'API 키 미설정')+' · 검토 대기 '+s.pending+'건'+(s.last_error_code?' · '+(errors[s.last_error_code]||'수집 오류 확인 필요'):'')+' · 마지막 정보 갱신 '+(s.last_refresh_at?new Date(s.last_refresh_at*1000).toLocaleString('ko-KR'):'기록 없음');}catch(e){$('#youtube-status').textContent=e.message;}}
 $('#youtube-channel-form').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{const r=await api('/api/youtube/channels',{channel:$('#youtube-channel').value.trim()});$('#youtube-channel').value='';$('#youtube-notice').textContent=r.title+' 채널을 추가했어요.';await status();}catch(error){$('#youtube-notice').textContent=error.message;}finally{b.disabled=false;}};
 $('#youtube-state').onchange=()=>load();$('#youtube-refresh').onclick=()=>{load();status();};$('#youtube-more').onclick=()=>load(true);$('#youtube-retry').onclick=async()=>{try{await api('/api/youtube/resume',{});await status();$('#youtube-notice').textContent='다음 예약 실행에서 연결을 다시 확인해요.';}catch(e){$('#youtube-notice').textContent=e.message;}};load();status();
})();
