(()=>{
 const $=s=>document.querySelector(s),node=(tag,text)=>{const n=document.createElement(tag);if(text)n.textContent=text;return n;};
 const errors={youtube_disabled:'유튜브 기능이 중지돼 있어요.',not_configured:'YouTube API 키 설정을 확인해 주세요.',provider_access:'YouTube API 사용 설정과 키 권한을 확인해 주세요.',quota_exceeded:'오늘의 조회 한도에 도달했어요.',unavailable:'공개된 영상 정보를 확인할 수 없어요.',review_conflict:'다른 작업에서 상태가 바뀌었어요. 새로고침 후 다시 확인해 주세요.',invalid_input:'영상 종류와 일반 영상 확인 항목을 확인해 주세요.'};
 const labels={pending:'검토 대기',kept:'표시 중',held:'보류',excluded:'제외'};let cursor=null,generation=0,state='pending';
 async function api(path,body,method='POST'){const r=await fetch(path,body?{method,headers:{'Content-Type':'application/json','X-Management-Action':'manage'},body:JSON.stringify(body)}:{});const d=await r.json();if(!r.ok)throw Error(r.status===401||r.status===403?'관리자 로그인 후 다시 열어 주세요.':errors[d.error]||'처리하지 못했어요. 새로고침 후 다시 시도해 주세요.');return d;}
 function option(label,values,value){const l=node('label',label),s=node('select');for(const [v,t]of values)s.add(new Option(t,v));s.value=value||'';l.append(s);return {label:l,select:s};}
 function card(p){const a=node('article');a.className='review-card youtube-review';const preview=node('div'),body=node('div');preview.className='youtube-preview';body.className='review-body';if(p.metadata?.thumbnailUrl){const img=node('img');img.src=p.metadata.thumbnailUrl;img.alt=p.metadata.title;img.loading='lazy';img.referrerPolicy='no-referrer';img.onerror=()=>img.remove();preview.append(img);}const link=node('a','YouTube에서 보기');link.className='review-link';link.href=p.url;link.target='_blank';link.rel='noopener noreferrer';preview.append(link);body.append(node('h2',p.metadata?.title||'영상 정보 확인 불가'),node('p',(p.metadata?.channelTitle||'채널 미확인')+' · '+labels[p.decision]),node('p',p.metadata?new Date(p.metadata.publishedAt).toLocaleDateString('ko-KR')+' · '+Math.floor(p.metadata.durationSeconds/60)+':'+String(Math.floor(p.metadata.durationSeconds%60)).padStart(2,'0'):'정보 갱신이 필요해요.'));
 const form=node('form'),category=option('관리자 분류',[['','종류 선택'],['fancam','개인 직캠'],['appearance','외부 출연'],['cosmo_live','COSMO 라이브'],['official','공식 콘텐츠'],['other','기타']],p.category),reason=option('제외 사유',[['SHORTS','Shorts'],['GROUP_STAGE','단체 무대'],['NOT_SEOYEON','서연 출연 아님'],['REUPLOAD','재업로드'],['FAN_EDIT','팬 편집본'],['OTHER','기타']],'SHORTS');
 const confirm=node('label','서연이 출연한 일반 영상임을 확인했습니다.'),check=node('input');confirm.className='youtube-confirm';check.type='checkbox';check.checked=p.format==='regular';confirm.prepend(check);form.className='review-filters';form.append(category.label,reason.label,confirm);const actions=node('div');actions.className='review-buttons';
 const message=node('p');message.setAttribute('role','status');let requestId=crypto.randomUUID(),lastPayload=null;
 for(const [decision,label]of [['kept','피드에 표시'],['excluded','제외'],['held','보류'],['pending','판단 취소']]){const b=node('button',label);b.type='button';b.setAttribute('aria-pressed',String(p.decision===decision));b.disabled=p.decision===decision||decision==='kept'&&(p.availability!=='available'||!p.metadata);b.onclick=async()=>{const payload={revision:p.revision,decision,category:category.select.value||null,format:decision==='excluded'&&reason.select.value==='SHORTS'?'shorts':check.checked?'regular':'unknown',reasonCode:decision==='kept'?'SEOYEON_CONFIRMED':decision==='excluded'?reason.select.value:'NEEDS_REVIEW'};const fingerprint=JSON.stringify(payload);if(lastPayload!==fingerprint){requestId=crypto.randomUUID();lastPayload=fingerprint;}actions.querySelectorAll('button').forEach(el=>el.disabled=true);try{await api('/api/youtube/review/'+p.videoId,{...payload,requestId},'PATCH');await load();}catch(e){message.textContent=e.message;form.querySelectorAll('button').forEach(el=>el.disabled=false);}};actions.append(b);}
 for(const p of body.querySelectorAll('p'))p.className='review-tags';if(p.discoveries?.length){const details=node('details'),summary=node('summary','발견 경로');details.className='review-help';details.append(summary,node('p',p.discoveries.map(v=>v.startsWith('search:')?'유튜브 검색':v.startsWith('channel:')?'등록한 채널':'직접 등록').filter((v,i,a)=>a.indexOf(v)===i).join(' · ')));body.append(details);}body.append(form,actions,message);a.append(preview,body);return a;}
 async function load(more=false){const version=++generation;$('#youtube-notice').textContent='불러오는 중…';$('#youtube-more').disabled=true;try{const q=new URLSearchParams({state});if(more&&cursor)q.set('cursor',cursor);const data=await api('/api/youtube/review?'+q);if(version!==generation)return;if(!more)$('#youtube-list').replaceChildren();$('#youtube-list').append(...data.posts.map(card));cursor=data.nextCursor;for(const b of document.querySelectorAll('[data-status]')){const key=b.dataset.status;b.setAttribute('aria-pressed',String(key===state));b.querySelector('span').textContent=key==='all'?data.counts.reduce((n,r)=>n+r.count,0):data.counts.find(r=>r.decision===key)?.count||0;}$('#youtube-more').hidden=!cursor;$('#youtube-notice').textContent=data.enabled?data.counts.map(r=>labels[r.decision]+' '+r.count).join(' · '):'유튜브 기능이 중지되어 있어요.';}catch(e){if(version===generation)$('#youtube-notice').textContent=e.message;}finally{if(version===generation)$('#youtube-more').disabled=false;}}
 document.querySelectorAll('[data-status]').forEach(b=>b.onclick=()=>{state=b.dataset.status;cursor=null;load();});$('#youtube-refresh').onclick=()=>load();$('#youtube-more').onclick=()=>load(true);load();
})();
