(()=>{
 const $=s=>document.querySelector(s),node=(tag,text)=>{const n=document.createElement(tag);if(text)n.textContent=text;return n;};
 const errors={youtube_disabled:'유튜브 기능이 중지돼 있어요.',not_configured:'YouTube API 키 설정을 확인해 주세요.',provider_access:'YouTube API 사용 설정과 키 권한을 확인해 주세요.',quota_exceeded:'오늘의 조회 한도에 도달했어요.',unavailable:'공개된 영상 정보를 확인할 수 없어요.',review_conflict:'다른 작업에서 상태가 바뀌었어요. 새로고침 후 다시 확인해 주세요.',invalid_input:'영상 종류와 일반 영상 확인 항목을 확인해 주세요.'};
 const labels={pending:'검토 대기',kept:'표시 중',held:'보류',excluded:'제외'};let cursor=null,generation=0,state='pending',bulkBusy=false,loading=false;const selected=new Map(),loaded=new Map();
 const collectionLabels={SHORTS:'Shorts 명시',SHORT_CLIP:'60초 미만',SUBJECT_UNCLEAR:'제목에서 서연 확인 안 됨',SOURCE_UNREGISTERED:'일반 콘텐츠 · 미등록 채널',FAN_EDIT:'팬 편집·모음 명시',METADATA_UNAVAILABLE:'영상 정보 없음'};
 async function api(path,body,method='POST'){const r=await fetch(path,body?{method,headers:{'Content-Type':'application/json','X-Management-Action':'manage'},body:JSON.stringify(body)}:{});const d=await r.json();if(!r.ok)throw Object.assign(Error(r.status===401||r.status===403?'관리자 로그인 후 다시 열어 주세요.':errors[d.error]||'처리하지 못했어요. 새로고침 후 다시 시도해 주세요.'),{status:r.status});return d;}
 function option(label,values,value){const l=node('label',label),s=node('select');for(const [v,t]of values)s.add(new Option(t,v));s.value=value||'';l.append(s);return {label:l,select:s};}
 function card(p){const a=node('article');a.className='review-card youtube-review';a.dataset.videoId=p.videoId;a.dataset.reviewId=p.videoId;loaded.set(p.videoId,p);const preview=node('div'),body=node('div');preview.className='youtube-preview';body.className='review-body';const thumbnail=node('div');thumbnail.className='youtube-thumbnail';preview.append(thumbnail);if(p.metadata?.thumbnailUrl){const img=node('img');img.src=p.metadata.thumbnailUrl;img.alt=p.metadata.title;img.loading='lazy';img.referrerPolicy='no-referrer';img.onerror=()=>thumbnail.replaceChildren(node('span','미리보기 없음'));thumbnail.append(img);}if(!p.metadata?.thumbnailUrl)thumbnail.append(node('span','미리보기 없음'));const link=node('a','YouTube에서 보기');link.className='review-link';link.href=p.url;link.target='_blank';link.rel='noopener noreferrer';preview.append(link);const selection=node('label'),select=node('input');selection.className='youtube-selection';select.type='checkbox';select.className='youtube-select';select.setAttribute('aria-label',(p.metadata?.title||p.videoId)+' 선택');select.onchange=()=>{$('#youtube-bulk-confirm').checked=false;if(select.checked)selected.set(p.videoId,{post:p});else selected.delete(p.videoId);updateSelection();};selection.prepend(select);const heading=node('div');heading.className='youtube-card-heading';heading.append(selection,node('h2',p.metadata?.title||'영상 정보 확인 불가'));body.append(heading); body.append(node('p',(p.metadata?.channelTitle||'채널 미확인')+' · '+labels[p.decision]),node('p',p.metadata?new Date(p.metadata.publishedAt).toLocaleDateString('ko-KR')+' · '+Math.floor(p.metadata.durationSeconds/60)+':'+String(Math.floor(p.metadata.durationSeconds%60)).padStart(2,'0'):'정보 갱신이 필요해요.'));
 if(p.collectionReason&&p.decision!=='kept'){const hint=node('p','자동 수집 기준 밖: '+collectionLabels[p.collectionReason]);hint.className='review-tags';body.append(hint);}
 const form=node('form'),category=option('관리자 분류',[['','종류 선택'],['fancam','개인 직캠'],['appearance','외부 출연'],['cosmo_live','COSMO 라이브'],['official','공식 콘텐츠'],['other','기타']],p.category),reason=option('제외 사유',[['SHORTS','Shorts'],['GROUP_STAGE','단체 무대'],['NOT_SEOYEON','서연 출연 아님'],['REUPLOAD','재업로드'],['FAN_EDIT','팬 편집본'],['OTHER','기타'],['COLLECTION_SCOPE','자동 수집 기준 밖']],'SHORTS');
 const confirm=node('label','서연이 출연한 일반 영상임을 확인했습니다.'),check=node('input');confirm.className='youtube-confirm';check.type='checkbox';check.checked=p.format==='regular';confirm.prepend(check);form.className='review-filters';form.append(category.label,reason.label,confirm);const actions=node('div');actions.className='review-buttons';
 const message=node('p');message.setAttribute('role','status');let requestId=crypto.randomUUID(),lastPayload=null;
 for(const [decision,label]of [['kept','피드에 표시'],['excluded','제외'],['held','보류'],['pending','판단 취소']]){const b=node('button',label);b.type='button';b.setAttribute('aria-pressed',String(p.decision===decision));b.disabled=p.decision===decision||decision==='kept'&&(p.availability!=='available'||!p.metadata);b.onclick=async()=>{if(bulkBusy)return;const focus=window.reviewFocus(b);const payload={revision:p.revision,decision,category:category.select.value||null,format:decision==='excluded'&&reason.select.value==='SHORTS'?'shorts':check.checked?'regular':'unknown',reasonCode:decision==='kept'?'SEOYEON_CONFIRMED':decision==='excluded'?reason.select.value:'NEEDS_REVIEW'};const fingerprint=JSON.stringify(payload);if(lastPayload!==fingerprint){requestId=crypto.randomUUID();lastPayload=fingerprint;}actions.querySelectorAll('button').forEach(el=>el.disabled=true);try{await api('/api/youtube/review/'+p.videoId,{...payload,requestId},'PATCH');await load();focus.restore();}catch(e){message.textContent=e.message;actions.querySelectorAll('button').forEach(el=>el.disabled=el.getAttribute('aria-pressed')==='true');}finally{focus.stop();}};actions.append(b);}
 for(const p of body.querySelectorAll('p'))p.className='review-tags';if(p.discoveries?.length){const details=node('details'),summary=node('summary','발견 경로');details.className='review-help';details.append(summary,node('p',p.discoveries.map(v=>v.startsWith('search:')?'유튜브 검색':v.startsWith('channel:')?'등록한 채널':'직접 등록').filter((v,i,a)=>a.indexOf(v)===i).join(' · ')));body.append(details);}body.append(form,actions,message);a.append(preview,body);return a;}
 async function load(more=false){loading=true;if(!more){selected.clear();$('#youtube-bulk-confirm').checked=false;}updateSelection();$('#youtube-bulk-notice').textContent='';const version=++generation;$('#youtube-notice').textContent='불러오는 중…';$('#youtube-more').disabled=true;try{const q=new URLSearchParams({state});if(more&&cursor)q.set('cursor',cursor);const data=await api('/api/youtube/review?'+q);if(version!==generation)return;if(!more){selected.clear();loaded.clear();$('#youtube-list').replaceChildren();}$('#youtube-list').append(...data.posts.map(card));updateSelection();cursor=data.nextCursor;for(const b of document.querySelectorAll('[data-status]')){const key=b.dataset.status;b.setAttribute('aria-pressed',String(key===state));b.querySelector('span').textContent=key==='all'?data.counts.reduce((n,r)=>n+r.count,0):data.counts.find(r=>r.decision===key)?.count||0;}$('#youtube-more').hidden=!cursor;$('#youtube-notice').textContent=data.enabled?($('#youtube-list').childElementCount?'':'이 상태의 영상이 없어요.'):'유튜브 기능이 중지되어 있어요.';}catch(e){if(version===generation)$('#youtube-notice').textContent=e.message;}finally{if(version===generation){loading=false;$('#youtube-more').disabled=false;updateSelection();}}}

 function updateSelection(){
  const boxes=[...document.querySelectorAll('.youtube-select')];for(const box of boxes){const id=box.closest('article').dataset.videoId;box.checked=selected.has(id);box.disabled=bulkBusy||loading;}
  const all=$('#youtube-select-all');all.disabled=bulkBusy||loading||!boxes.length;all.checked=boxes.length>0&&boxes.every(b=>b.checked);all.indeterminate=boxes.some(b=>b.checked)&&!all.checked;
  const keep=$('#youtube-bulk-action').value==='kept';$('#youtube-bulk-controls').hidden=!selected.size;$('#youtube-selected-count').textContent=selected.size?selected.size+'개 선택':'';
  $('#youtube-bulk-category-field').hidden=!keep;$('#youtube-bulk-confirm-field').hidden=!keep;$('#youtube-bulk-reason-field').hidden=keep;
  $('#youtube-bulk-apply').disabled=bulkBusy||loading||!selected.size||keep&&(!$('#youtube-bulk-category').value||!$('#youtube-bulk-confirm').checked);
  $('#youtube-bulk-apply').textContent=(keep?'피드에 표시':'선택 제외')+' ('+selected.size+')';
 }
 $('#youtube-select-all').onchange=()=>{const checked=$('#youtube-select-all').checked;$('#youtube-bulk-confirm').checked=false;for(const p of loaded.values()){if(checked)selected.set(p.videoId,selected.get(p.videoId)||{post:p});else selected.delete(p.videoId);}updateSelection();};
 $('#youtube-bulk-action').onchange=()=>{$('#youtube-bulk-confirm').checked=false;updateSelection();};
 $('#youtube-bulk-category').onchange=()=>{$('#youtube-bulk-confirm').checked=false;updateSelection();};$('#youtube-bulk-confirm').onchange=updateSelection;
 $('#youtube-bulk-apply').onclick=async()=>{
  const decision=$('#youtube-bulk-action').value,keep=decision==='kept',category=$('#youtube-bulk-category').value;
  if(bulkBusy||loading||!selected.size||keep&&(!category||!$('#youtube-bulk-confirm').checked))return;
  bulkBusy=true;const entries=[...selected.values()],reasonCode=keep?'SEOYEON_CONFIRMED':$('#youtube-bulk-reason').value;let saved=0,failed=0;
  const controls=[...document.querySelectorAll('main button,main input,main select')].map(el=>[el,el.disabled]);controls.forEach(([el])=>el.disabled=true);
  try{for(const entry of entries){const p=entry.post;const payload={revision:p.revision,decision,category:keep?category:p.category,format:keep?'regular':reasonCode==='SHORTS'?'shorts':p.format,reasonCode};const fingerprint=JSON.stringify(payload);if(entry.fingerprint!==fingerprint){entry.fingerprint=fingerprint;entry.requestId=crypto.randomUUID();}
   $('#youtube-bulk-notice').textContent='선택 항목 처리 중 '+(saved+failed+1)+' / '+entries.length;
   try{await api('/api/youtube/review/'+p.videoId,{...payload,requestId:entry.requestId},'PATCH');saved++;}catch(e){failed++;if(![409,422].includes(e.status)){failed+=entries.length-saved-failed;break;}}
  }await load();$('#youtube-bulk-notice').textContent=failed?saved+'개 '+(keep?'표시':'제외')+' · '+failed+'개 처리 실패. 목록을 새로고침해 확인해 주세요.':keep?saved+'개를 피드에 표시했어요.':saved+'개를 제외했어요. 제외 탭에서 다시 검토할 수 있어요.';
  }finally{bulkBusy=false;controls.forEach(([el,disabled])=>{if(el.isConnected)el.disabled=disabled;});updateSelection();$('#youtube-select-all').focus();}
 };
 document.querySelectorAll('[data-status]').forEach(b=>b.onclick=()=>{state=b.dataset.status;cursor=null;load();});$('#youtube-refresh').onclick=()=>load();$('#youtube-more').onclick=()=>load(true);load();
})();
